package logic.enumeration;

public enum VGConsole {
	COMPUTER, NES, NINTENDO_3DS, NINTENDO_DS, NINTENDO_SWITCH, NINTENDO_WII, NINTENDO_WII_U, OTHER, PLAY_STATION, PLAY_STATION_2, PLAY_STATION_3, PLAY_STATION_4, PLAY_STATION_5, SNES, XBOX_360, XBOX_ONE, XBOX_SERIES;
}
